import 'package:flutter/material.dart';

import 'prop_sprite_catalog.dart';
import 'prop_state.dart';
import 'room_hotspots.dart';

enum PropSmashStyle {
  shatter,
  spill,
  tipOver,
  crack,
  explode,
  smashFlat,
  splash,
}

/// A smashable / throwable prop inside a room.
class RoomProp {
  const RoomProp({
    required this.id,
    required this.label,
    required this.icon,
    required this.color,
    required this.align,
    required this.size,
    required this.style,
    this.throwable = false,
    this.reactions = const {},
    this.spriteAsset,
    this.materialType,
    this.sizeNorm,
    this.aspectRatio,
    this.zIndex,
    this.anchor,
  });

  final String id;
  final String label;
  final IconData icon;
  final Color color;

  /// Position in the room stage (Alignment).
  final Alignment align;
  final double size;
  final PropSmashStyle style;
  final bool throwable;

  /// Special reactions when another prop is thrown at this one.
  /// key = thrown prop id (or generic 'glass'), value = reaction style + message.
  final Map<String, PropReaction> reactions;

  final String? spriteAsset;
  final PropMaterial? materialType;
  final double? sizeNorm;
  final double? aspectRatio;
  final int? zIndex;
  final Offset? anchor;

  PropMaterial get effectiveMaterial =>
      materialType ?? PropSpriteCatalog.materialFor(id);

  double get effectiveSizeNorm =>
      sizeNorm ?? PropSpriteCatalog.sizeNormFor(id);

  double get effectiveAspectRatio =>
      aspectRatio ?? PropSpriteCatalog.aspectRatioFor(id);

  int get effectiveZIndex => zIndex ?? PropSpriteCatalog.zIndexFor(id);

  String resolvedSprite(String roomId) =>
      spriteAsset ?? 'assets/rooms/props/${roomId}_$id.png';

  Offset anchorFor(String roomId) =>
      anchor ??
      RoomHotspots.forProp(
        roomId: roomId,
        propId: id,
        fallback: align,
      );
}

class PropReaction {
  const PropReaction({
    required this.style,
    required this.message,
    required this.sfxHint,
  });

  final PropSmashStyle style;
  final String message;
  final String sfxHint;
}

class RoomSetup {
  const RoomSetup({
    required this.id,
    required this.name,
    required this.subtitle,
    required this.icon,
    required this.accent,
    required this.gradient,
    required this.props,
    this.assetPath,
    this.spriteMode = true,
    this.baseAssetPath,
  });

  final String id;
  final String name;
  final String subtitle;
  final IconData icon;
  final Color accent;
  final List<Color> gradient;
  final List<RoomProp> props;

  /// Illustrated room background under `assets/rooms/`.
  final String? assetPath;

  /// When true, uses clean base + layered prop sprites instead of hotspot pins.
  final bool spriteMode;
  final String? baseAssetPath;

  String get resolvedAsset => assetPath ?? 'assets/rooms/$id.png';

  String get resolvedBaseAsset =>
      baseAssetPath ?? (spriteMode ? 'assets/rooms/${id}_base.png' : resolvedAsset);

  static RoomSetup? findById(String id) {
    for (final r in all) {
      if (r.id == id) return r;
    }
    return null;
  }

  static const List<RoomSetup> all = [
    RoomSetup(
      id: 'kitchen',
      name: 'Kitchen',
      subtitle: 'Plates, glasses, chaos',
      icon: Icons.kitchen,
      accent: Color(0xFFFF8A65),
      gradient: [Color(0xFF3E2723), Color(0xFF1A1A2E)],
      baseAssetPath: 'assets/rooms/kitchen_base.png',
      props: [
        RoomProp(
          id: 'glass',
          label: 'Glass',
          icon: Icons.local_bar,
          color: Color(0xFF81D4FA),
          align: Alignment(-0.72, 0.32),
          size: 52,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'plate',
          label: 'Plate',
          icon: Icons.dinner_dining,
          color: Color(0xFFFFE082),
          align: Alignment(0.02, 0.28),
          size: 56,
          style: PropSmashStyle.shatter,
        ),
        RoomProp(
          id: 'mug',
          label: 'Mug',
          icon: Icons.coffee,
          color: Color(0xFFA1887F),
          align: Alignment(0.38, 0.22),
          size: 48,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'blender',
          label: 'Blender',
          icon: Icons.blender,
          color: Color(0xFF90A4AE),
          align: Alignment(-0.12, -0.08),
          size: 64,
          style: PropSmashStyle.explode,
        ),
        RoomProp(
          id: 'chair',
          label: 'Chair',
          icon: Icons.chair,
          color: Color(0xFF8D6E63),
          align: Alignment(0.78, 0.42),
          size: 70,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'table',
          label: 'Table',
          icon: Icons.table_restaurant,
          color: Color(0xFF6D4C41),
          align: Alignment(-0.02, 0.38),
          size: 78,
          style: PropSmashStyle.smashFlat,
          reactions: {
            'glass': PropReaction(
              style: PropSmashStyle.spill,
              message: 'Water spills across the table!',
              sfxHint: 'splash',
            ),
          },
        ),
      ],
    ),
    RoomSetup(
      id: 'bathroom',
      name: 'Bathroom',
      subtitle: 'Mirror, tiles, splash zone',
      icon: Icons.bathtub,
      accent: Color(0xFF4FC3F7),
      gradient: [Color(0xFF01579B), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'mirror',
          label: 'Mirror',
          icon: Icons.crop_portrait,
          color: Color(0xFFB0BEC5),
          align: Alignment(0.0, -0.45),
          size: 72,
          style: PropSmashStyle.shatter,
          reactions: {
            'glass': PropReaction(
              style: PropSmashStyle.shatter,
              message: 'Mirror shatters into a thousand cracks!',
              sfxHint: 'smash',
            ),
          },
        ),
        RoomProp(
          id: 'glass',
          label: 'Tumbler',
          icon: Icons.local_drink,
          color: Color(0xFF80DEEA),
          align: Alignment(-0.55, 0.1),
          size: 48,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'bottle',
          label: 'Bottle',
          icon: Icons.science,
          color: Color(0xFFCE93D8),
          align: Alignment(0.5, 0.05),
          size: 50,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'soap',
          label: 'Soap dish',
          icon: Icons.soap,
          color: Color(0xFFFFF59D),
          align: Alignment(-0.2, 0.35),
          size: 44,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'toilet',
          label: 'Lid',
          icon: Icons.wc,
          color: Color(0xFFECEFF1),
          align: Alignment(0.55, 0.5),
          size: 64,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'towel',
          label: 'Towel rack',
          icon: Icons.dry_cleaning,
          color: Color(0xFF80CBC4),
          align: Alignment(-0.6, -0.2),
          size: 54,
          style: PropSmashStyle.tipOver,
        ),
      ],
    ),
    RoomSetup(
      id: 'office',
      name: 'Office',
      subtitle: 'Desk rage approved',
      icon: Icons.business_center,
      accent: Color(0xFF90CAF9),
      gradient: [Color(0xFF263238), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'monitor',
          label: 'Monitor',
          icon: Icons.desktop_windows,
          color: Color(0xFF78909C),
          align: Alignment(0.0, -0.2),
          size: 70,
          style: PropSmashStyle.crack,
        ),
        RoomProp(
          id: 'keyboard',
          label: 'Keyboard',
          icon: Icons.keyboard,
          color: Color(0xFF546E7A),
          align: Alignment(0.05, 0.25),
          size: 56,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'mug',
          label: 'Coffee',
          icon: Icons.coffee,
          color: Color(0xFFBCAAA4),
          align: Alignment(0.55, 0.05),
          size: 46,
          style: PropSmashStyle.spill,
          throwable: true,
        ),
        RoomProp(
          id: 'chair',
          label: 'Office chair',
          icon: Icons.event_seat,
          color: Color(0xFF455A64),
          align: Alignment(-0.55, 0.45),
          size: 68,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'lamp',
          label: 'Desk lamp',
          icon: Icons.light,
          color: Color(0xFFFFF176),
          align: Alignment(-0.45, -0.15),
          size: 50,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'plant',
          label: 'Plant',
          icon: Icons.yard,
          color: Color(0xFF81C784),
          align: Alignment(0.6, 0.45),
          size: 52,
          style: PropSmashStyle.spill,
        ),
      ],
    ),
    RoomSetup(
      id: 'cabin',
      name: 'Cabin',
      subtitle: 'Rustic smash therapy',
      icon: Icons.cabin,
      accent: Color(0xFFA1887F),
      gradient: [Color(0xFF4E342E), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'lantern',
          label: 'Lantern',
          icon: Icons.fireplace,
          color: Color(0xFFFFB74D),
          align: Alignment(-0.4, -0.1),
          size: 52,
          style: PropSmashStyle.explode,
        ),
        RoomProp(
          id: 'mug',
          label: 'Tin mug',
          icon: Icons.emoji_food_beverage,
          color: Color(0xFF8D6E63),
          align: Alignment(0.35, 0.05),
          size: 46,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'chair',
          label: 'Wood chair',
          icon: Icons.chair_alt,
          color: Color(0xFF6D4C41),
          align: Alignment(0.55, 0.45),
          size: 66,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'table',
          label: 'Cabin table',
          icon: Icons.table_bar,
          color: Color(0xFF5D4037),
          align: Alignment(-0.1, 0.4),
          size: 74,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'window',
          label: 'Window',
          icon: Icons.window,
          color: Color(0xFF81D4FA),
          align: Alignment(0.0, -0.5),
          size: 70,
          style: PropSmashStyle.shatter,
          reactions: {
            'mug': PropReaction(
              style: PropSmashStyle.shatter,
              message: 'Window pane cracks!',
              sfxHint: 'crack',
            ),
          },
        ),
        RoomProp(
          id: 'logs',
          label: 'Firewood',
          icon: Icons.forest,
          color: Color(0xFF795548),
          align: Alignment(-0.6, 0.5),
          size: 58,
          style: PropSmashStyle.smashFlat,
        ),
      ],
    ),
    RoomSetup(
      id: 'living',
      name: 'Living Room',
      subtitle: 'Sofa, TV, full chaos',
      icon: Icons.weekend,
      accent: Color(0xFFCE93D8),
      gradient: [Color(0xFF4A148C), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'tv',
          label: 'TV',
          icon: Icons.tv,
          color: Color(0xFF78909C),
          align: Alignment(0.62, -0.22),
          size: 72,
          style: PropSmashStyle.crack,
        ),
        RoomProp(
          id: 'sofa',
          label: 'Sofa',
          icon: Icons.weekend,
          color: Color(0xFF7E57C2),
          align: Alignment(-0.42, 0.28),
          size: 88,
          style: PropSmashStyle.smashFlat,
          reactions: {
            'glass': PropReaction(
              style: PropSmashStyle.spill,
              message: 'Drink spills all over the sofa!',
              sfxHint: 'splash',
            ),
          },
        ),
        RoomProp(
          id: 'glass',
          label: 'Wine glass',
          icon: Icons.wine_bar,
          color: Color(0xFFEF9A9A),
          align: Alignment(0.08, 0.38),
          size: 48,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'vase',
          label: 'Vase',
          icon: Icons.local_florist,
          color: Color(0xFFF48FB1),
          align: Alignment(0.72, 0.08),
          size: 54,
          style: PropSmashStyle.shatter,
        ),
        RoomProp(
          id: 'lamp',
          label: 'Floor lamp',
          icon: Icons.lightbulb,
          color: Color(0xFFFFF59D),
          align: Alignment(-0.68, -0.05),
          size: 58,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'remote',
          label: 'Remote',
          icon: Icons.settings_remote,
          color: Color(0xFF90A4AE),
          align: Alignment(-0.15, 0.42),
          size: 40,
          style: PropSmashStyle.smashFlat,
          throwable: true,
        ),
      ],
    ),
    RoomSetup(
      id: 'bedroom',
      name: 'Bedroom',
      subtitle: 'Lamp, clock, pillow storm',
      icon: Icons.bed,
      accent: Color(0xFF80CBC4),
      gradient: [Color(0xFF004D40), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'lamp',
          label: 'Night lamp',
          icon: Icons.wb_incandescent,
          color: Color(0xFFFFE082),
          align: Alignment(-0.55, -0.05),
          size: 50,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'clock',
          label: 'Alarm',
          icon: Icons.alarm,
          color: Color(0xFFFFAB91),
          align: Alignment(0.5, -0.1),
          size: 46,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'mirror',
          label: 'Mirror',
          icon: Icons.crop_portrait,
          color: Color(0xFFB0BEC5),
          align: Alignment(0.0, -0.45),
          size: 64,
          style: PropSmashStyle.shatter,
        ),
        RoomProp(
          id: 'pillow',
          label: 'Pillow',
          icon: Icons.airline_seat_individual_suite,
          color: Color(0xFFE0F2F1),
          align: Alignment(-0.15, 0.35),
          size: 60,
          style: PropSmashStyle.smashFlat,
          throwable: true,
        ),
        RoomProp(
          id: 'frame',
          label: 'Photo frame',
          icon: Icons.photo,
          color: Color(0xFFA1887F),
          align: Alignment(0.55, 0.35),
          size: 48,
          style: PropSmashStyle.shatter,
        ),
        RoomProp(
          id: 'glass',
          label: 'Water glass',
          icon: Icons.local_drink,
          color: Color(0xFF81D4FA),
          align: Alignment(-0.5, 0.45),
          size: 44,
          style: PropSmashStyle.spill,
          throwable: true,
        ),
      ],
    ),
    RoomSetup(
      id: 'garage',
      name: 'Garage',
      subtitle: 'Tools, cans, wreck it',
      icon: Icons.garage,
      accent: Color(0xFFFFB74D),
      gradient: [Color(0xFF37474F), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'can',
          label: 'Paint can',
          icon: Icons.format_paint,
          color: Color(0xFFFF7043),
          align: Alignment(-0.5, 0.2),
          size: 52,
          style: PropSmashStyle.spill,
          throwable: true,
        ),
        RoomProp(
          id: 'toolbox',
          label: 'Toolbox',
          icon: Icons.handyman,
          color: Color(0xFF78909C),
          align: Alignment(0.4, 0.25),
          size: 58,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'shelf',
          label: 'Shelf',
          icon: Icons.inventory_2,
          color: Color(0xFF90A4AE),
          align: Alignment(0.0, -0.35),
          size: 70,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'bulb',
          label: 'Bulb',
          icon: Icons.lightbulb_outline,
          color: Color(0xFFFFF176),
          align: Alignment(0.55, -0.2),
          size: 42,
          style: PropSmashStyle.shatter,
        ),
        RoomProp(
          id: 'bucket',
          label: 'Bucket',
          icon: Icons.cleaning_services,
          color: Color(0xFF4DB6AC),
          align: Alignment(-0.55, 0.5),
          size: 54,
          style: PropSmashStyle.spill,
        ),
        RoomProp(
          id: 'chair',
          label: 'Stool',
          icon: Icons.chair_alt,
          color: Color(0xFF8D6E63),
          align: Alignment(0.55, 0.5),
          size: 56,
          style: PropSmashStyle.tipOver,
        ),
      ],
    ),
    RoomSetup(
      id: 'dining',
      name: 'Dining Room',
      subtitle: 'Fine china, free chaos',
      icon: Icons.restaurant,
      accent: Color(0xFFFFCC80),
      gradient: [Color(0xFF5D4037), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'plate',
          label: 'China',
          icon: Icons.dinner_dining,
          color: Color(0xFFFFECB3),
          align: Alignment(-0.2, 0.05),
          size: 54,
          style: PropSmashStyle.shatter,
        ),
        RoomProp(
          id: 'glass',
          label: 'Goblet',
          icon: Icons.liquor,
          color: Color(0xFF80DEEA),
          align: Alignment(0.35, 0.0),
          size: 48,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'chandelier',
          label: 'Chandelier',
          icon: Icons.auto_awesome,
          color: Color(0xFFFFF59D),
          align: Alignment(0.0, -0.55),
          size: 64,
          style: PropSmashStyle.shatter,
        ),
        RoomProp(
          id: 'chair',
          label: 'Dining chair',
          icon: Icons.chair,
          color: Color(0xFF6D4C41),
          align: Alignment(-0.6, 0.45),
          size: 64,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'table',
          label: 'Dining table',
          icon: Icons.table_restaurant,
          color: Color(0xFF5D4037),
          align: Alignment(0.1, 0.45),
          size: 80,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'vase',
          label: 'Centerpiece',
          icon: Icons.spa,
          color: Color(0xFFF48FB1),
          align: Alignment(0.55, 0.2),
          size: 50,
          style: PropSmashStyle.shatter,
        ),
      ],
    ),
    RoomSetup(
      id: 'hotel',
      name: 'Hotel Suite',
      subtitle: 'Mini-bar meltdown',
      icon: Icons.hotel,
      accent: Color(0xFFFFD54F),
      gradient: [Color(0xFF311B92), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'minibar',
          label: 'Mini-bar',
          icon: Icons.kitchen,
          color: Color(0xFF7986CB),
          align: Alignment(-0.55, 0.15),
          size: 60,
          style: PropSmashStyle.explode,
        ),
        RoomProp(
          id: 'glass',
          label: 'Glass',
          icon: Icons.local_bar,
          color: Color(0xFF81D4FA),
          align: Alignment(0.2, 0.05),
          size: 46,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'tv',
          label: 'TV',
          icon: Icons.tv,
          color: Color(0xFF90A4AE),
          align: Alignment(0.5, -0.25),
          size: 64,
          style: PropSmashStyle.crack,
        ),
        RoomProp(
          id: 'lamp',
          label: 'Lamp',
          icon: Icons.light,
          color: Color(0xFFFFE082),
          align: Alignment(-0.45, -0.25),
          size: 50,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'tray',
          label: 'Room service',
          icon: Icons.room_service,
          color: Color(0xFFFFCC80),
          align: Alignment(0.0, 0.4),
          size: 58,
          style: PropSmashStyle.spill,
        ),
        RoomProp(
          id: 'phone',
          label: 'Phone',
          icon: Icons.phone,
          color: Color(0xFFEF9A9A),
          align: Alignment(0.55, 0.4),
          size: 42,
          style: PropSmashStyle.smashFlat,
          throwable: true,
        ),
      ],
    ),
    RoomSetup(
      id: 'classroom',
      name: 'Classroom',
      subtitle: 'Chalkboard catharsis',
      icon: Icons.school,
      accent: Color(0xFFAED581),
      gradient: [Color(0xFF33691E), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'board',
          label: 'Board',
          icon: Icons.dashboard,
          color: Color(0xFF558B2F),
          align: Alignment(0.0, -0.4),
          size: 78,
          style: PropSmashStyle.crack,
        ),
        RoomProp(
          id: 'desk',
          label: 'Desk',
          icon: Icons.desk,
          color: Color(0xFF8D6E63),
          align: Alignment(-0.2, 0.4),
          size: 70,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'chair',
          label: 'Chair',
          icon: Icons.event_seat,
          color: Color(0xFF6D4C41),
          align: Alignment(0.45, 0.45),
          size: 58,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'globe',
          label: 'Globe',
          icon: Icons.public,
          color: Color(0xFF4FC3F7),
          align: Alignment(0.55, -0.05),
          size: 50,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'books',
          label: 'Books',
          icon: Icons.menu_book,
          color: Color(0xFFFFB74D),
          align: Alignment(-0.55, 0.05),
          size: 52,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'apple',
          label: 'Apple',
          icon: Icons.apple,
          color: Color(0xFFEF5350),
          align: Alignment(-0.45, 0.35),
          size: 40,
          style: PropSmashStyle.smashFlat,
          throwable: true,
        ),
      ],
    ),
    RoomSetup(
      id: 'locker',
      name: 'Gym Locker',
      subtitle: 'Lockers, bottles, steam',
      icon: Icons.fitness_center,
      accent: Color(0xFF80CBC4),
      gradient: [Color(0xFF00695C), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'locker',
          label: 'Locker',
          icon: Icons.door_sliding,
          color: Color(0xFF78909C),
          align: Alignment(-0.45, -0.15),
          size: 70,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'bottle',
          label: 'Bottle',
          icon: Icons.sports_gymnastics,
          color: Color(0xFF4FC3F7),
          align: Alignment(0.35, 0.1),
          size: 48,
          style: PropSmashStyle.spill,
          throwable: true,
        ),
        RoomProp(
          id: 'bench',
          label: 'Bench',
          icon: Icons.weekend,
          color: Color(0xFF8D6E63),
          align: Alignment(0.1, 0.5),
          size: 72,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'mirror',
          label: 'Mirror',
          icon: Icons.crop_portrait,
          color: Color(0xFFB0BEC5),
          align: Alignment(0.55, -0.3),
          size: 60,
          style: PropSmashStyle.shatter,
        ),
        RoomProp(
          id: 'scale',
          label: 'Scale',
          icon: Icons.monitor_weight,
          color: Color(0xFF90A4AE),
          align: Alignment(-0.55, 0.45),
          size: 50,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'towel',
          label: 'Towel',
          icon: Icons.dry_cleaning,
          color: Color(0xFFE0F7FA),
          align: Alignment(0.55, 0.35),
          size: 46,
          style: PropSmashStyle.tipOver,
        ),
      ],
    ),
    RoomSetup(
      id: 'cafe',
      name: 'Cafe',
      subtitle: 'Cups, chairs, latte rage',
      icon: Icons.local_cafe,
      accent: Color(0xFFBCAAA4),
      gradient: [Color(0xFF3E2723), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'cup',
          label: 'Latte',
          icon: Icons.coffee,
          color: Color(0xFFD7CCC8),
          align: Alignment(-0.25, 0.05),
          size: 48,
          style: PropSmashStyle.spill,
          throwable: true,
        ),
        RoomProp(
          id: 'chair',
          label: 'Chair',
          icon: Icons.chair,
          color: Color(0xFF8D6E63),
          align: Alignment(0.5, 0.4),
          size: 60,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'table',
          label: 'Cafe table',
          icon: Icons.table_bar,
          color: Color(0xFF6D4C41),
          align: Alignment(-0.1, 0.4),
          size: 68,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'pastry',
          label: 'Pastry case',
          icon: Icons.cake,
          color: Color(0xFFFFCC80),
          align: Alignment(-0.55, -0.2),
          size: 56,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'sign',
          label: 'Menu board',
          icon: Icons.menu_book,
          color: Color(0xFFA1887F),
          align: Alignment(0.45, -0.3),
          size: 54,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'glass',
          label: 'Iced drink',
          icon: Icons.local_drink,
          color: Color(0xFF80CBC4),
          align: Alignment(0.2, 0.05),
          size: 44,
          style: PropSmashStyle.spill,
          throwable: true,
        ),
      ],
    ),
    RoomSetup(
      id: 'studio',
      name: 'Studio Apt',
      subtitle: 'Tiny space, big mess',
      icon: Icons.apartment,
      accent: Color(0xFF90CAF9),
      gradient: [Color(0xFF0D47A1), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'fridge',
          label: 'Mini fridge',
          icon: Icons.kitchen,
          color: Color(0xFF90A4AE),
          align: Alignment(-0.55, 0.1),
          size: 60,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'bed',
          label: 'Murphy bed',
          icon: Icons.bed,
          color: Color(0xFF7986CB),
          align: Alignment(0.4, 0.4),
          size: 70,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'glass',
          label: 'Glass',
          icon: Icons.local_bar,
          color: Color(0xFF81D4FA),
          align: Alignment(0.1, -0.05),
          size: 44,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'lamp',
          label: 'Lamp',
          icon: Icons.lightbulb,
          color: Color(0xFFFFF59D),
          align: Alignment(0.55, -0.2),
          size: 48,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'speaker',
          label: 'Speaker',
          icon: Icons.speaker,
          color: Color(0xFF78909C),
          align: Alignment(-0.4, -0.35),
          size: 50,
          style: PropSmashStyle.crack,
        ),
        RoomProp(
          id: 'plant',
          label: 'Plant',
          icon: Icons.grass,
          color: Color(0xFF81C784),
          align: Alignment(-0.55, 0.5),
          size: 50,
          style: PropSmashStyle.spill,
        ),
      ],
    ),
    RoomSetup(
      id: 'gameroom',
      name: 'Game Room',
      subtitle: 'Controllers optional',
      icon: Icons.sports_esports,
      accent: Color(0xFFEA80FC),
      gradient: [Color(0xFF6A1B9A), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'console',
          label: 'Console',
          icon: Icons.videogame_asset,
          color: Color(0xFFCE93D8),
          align: Alignment(0.0, 0.15),
          size: 58,
          style: PropSmashStyle.crack,
        ),
        RoomProp(
          id: 'controller',
          label: 'Controller',
          icon: Icons.gamepad,
          color: Color(0xFFAB47BC),
          align: Alignment(-0.45, 0.3),
          size: 46,
          style: PropSmashStyle.smashFlat,
          throwable: true,
        ),
        RoomProp(
          id: 'tv',
          label: 'Screen',
          icon: Icons.tv,
          color: Color(0xFF90A4AE),
          align: Alignment(0.0, -0.4),
          size: 72,
          style: PropSmashStyle.crack,
        ),
        RoomProp(
          id: 'chair',
          label: 'Gamer chair',
          icon: Icons.event_seat,
          color: Color(0xFFE040FB),
          align: Alignment(0.55, 0.4),
          size: 64,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'snack',
          label: 'Snack bowl',
          icon: Icons.fastfood,
          color: Color(0xFFFFB74D),
          align: Alignment(-0.5, -0.05),
          size: 48,
          style: PropSmashStyle.spill,
        ),
        RoomProp(
          id: 'can',
          label: 'Soda',
          icon: Icons.sports_bar,
          color: Color(0xFFEF5350),
          align: Alignment(0.4, 0.0),
          size: 42,
          style: PropSmashStyle.spill,
          throwable: true,
        ),
      ],
    ),
    RoomSetup(
      id: 'laundry',
      name: 'Laundry',
      subtitle: 'Spin cycle of rage',
      icon: Icons.local_laundry_service,
      accent: Color(0xFF80DEEA),
      gradient: [Color(0xFF006064), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'washer',
          label: 'Washer',
          icon: Icons.local_laundry_service,
          color: Color(0xFF4DD0E1),
          align: Alignment(-0.4, 0.15),
          size: 70,
          style: PropSmashStyle.explode,
        ),
        RoomProp(
          id: 'dryer',
          label: 'Dryer',
          icon: Icons.local_laundry_service,
          color: Color(0xFF26C6DA),
          align: Alignment(0.4, 0.15),
          size: 70,
          style: PropSmashStyle.explode,
        ),
        RoomProp(
          id: 'basket',
          label: 'Basket',
          icon: Icons.shopping_basket,
          color: Color(0xFFFFCC80),
          align: Alignment(-0.55, 0.5),
          size: 54,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'detergent',
          label: 'Detergent',
          icon: Icons.science,
          color: Color(0xFF81D4FA),
          align: Alignment(0.55, 0.45),
          size: 46,
          style: PropSmashStyle.spill,
          throwable: true,
        ),
        RoomProp(
          id: 'iron',
          label: 'Iron',
          icon: Icons.hardware,
          color: Color(0xFF90A4AE),
          align: Alignment(0.1, -0.25),
          size: 48,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'shelf',
          label: 'Shelf',
          icon: Icons.inventory_2,
          color: Color(0xFF80CBC4),
          align: Alignment(0.0, -0.5),
          size: 64,
          style: PropSmashStyle.tipOver,
        ),
      ],
    ),
    RoomSetup(
      id: 'balcony',
      name: 'Balcony',
      subtitle: 'Outdoor smash vibes',
      icon: Icons.balcony,
      accent: Color(0xFF81C784),
      gradient: [Color(0xFF1B5E20), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'plant',
          label: 'Planter',
          icon: Icons.spa,
          color: Color(0xFF66BB6A),
          align: Alignment(-0.5, 0.2),
          size: 56,
          style: PropSmashStyle.spill,
        ),
        RoomProp(
          id: 'chair',
          label: 'Lounge chair',
          icon: Icons.beach_access,
          color: Color(0xFFFFCC80),
          align: Alignment(0.4, 0.4),
          size: 64,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'glass',
          label: 'Drink',
          icon: Icons.local_bar,
          color: Color(0xFF80DEEA),
          align: Alignment(0.05, 0.05),
          size: 44,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'table',
          label: 'Side table',
          icon: Icons.table_bar,
          color: Color(0xFFA1887F),
          align: Alignment(-0.15, 0.4),
          size: 58,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'lantern',
          label: 'Lantern',
          icon: Icons.nightlight,
          color: Color(0xFFFFE082),
          align: Alignment(0.55, -0.15),
          size: 48,
          style: PropSmashStyle.explode,
        ),
        RoomProp(
          id: 'rail',
          label: 'Rail decor',
          icon: Icons.fence,
          color: Color(0xFFB0BEC5),
          align: Alignment(0.0, -0.45),
          size: 70,
          style: PropSmashStyle.tipOver,
        ),
      ],
    ),
    RoomSetup(
      id: 'workshop',
      name: 'Workshop',
      subtitle: 'Sawdust & mayhem',
      icon: Icons.carpenter,
      accent: Color(0xFFFFB74D),
      gradient: [Color(0xFFBF360C), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'saw',
          label: 'Saw',
          icon: Icons.content_cut,
          color: Color(0xFF90A4AE),
          align: Alignment(-0.4, 0.0),
          size: 52,
          style: PropSmashStyle.smashFlat,
          throwable: true,
        ),
        RoomProp(
          id: 'bench',
          label: 'Workbench',
          icon: Icons.table_restaurant,
          color: Color(0xFF8D6E63),
          align: Alignment(0.1, 0.4),
          size: 76,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'jar',
          label: 'Screw jar',
          icon: Icons.inventory_2,
          color: Color(0xFFFFCC80),
          align: Alignment(0.5, 0.05),
          size: 46,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'radio',
          label: 'Radio',
          icon: Icons.radio,
          color: Color(0xFFFF8A65),
          align: Alignment(-0.5, -0.3),
          size: 50,
          style: PropSmashStyle.crack,
        ),
        RoomProp(
          id: 'shelf',
          label: 'Tool wall',
          icon: Icons.handyman,
          color: Color(0xFFA1887F),
          align: Alignment(0.45, -0.35),
          size: 64,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'can',
          label: 'Oil can',
          icon: Icons.science,
          color: Color(0xFF78909C),
          align: Alignment(-0.55, 0.45),
          size: 50,
          style: PropSmashStyle.spill,
        ),
      ],
    ),
    RoomSetup(
      id: 'penthouse',
      name: 'Penthouse',
      subtitle: 'Luxury demolition',
      icon: Icons.location_city,
      accent: Color(0xFFFFD54F),
      gradient: [Color(0xFF212121), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'sculpture',
          label: 'Sculpture',
          icon: Icons.museum,
          color: Color(0xFFE0E0E0),
          align: Alignment(-0.45, 0.0),
          size: 58,
          style: PropSmashStyle.shatter,
        ),
        RoomProp(
          id: 'glass',
          label: 'Champagne',
          icon: Icons.celebration,
          color: Color(0xFFFFF59D),
          align: Alignment(0.2, 0.05),
          size: 48,
          style: PropSmashStyle.shatter,
          throwable: true,
        ),
        RoomProp(
          id: 'sofa',
          label: 'Designer sofa',
          icon: Icons.weekend,
          color: Color(0xFFBDBDBD),
          align: Alignment(0.1, 0.5),
          size: 84,
          style: PropSmashStyle.smashFlat,
          reactions: {
            'glass': PropReaction(
              style: PropSmashStyle.spill,
              message: 'Champagne soaks the designer sofa!',
              sfxHint: 'splash',
            ),
          },
        ),
        RoomProp(
          id: 'window',
          label: 'Panorama',
          icon: Icons.window,
          color: Color(0xFF81D4FA),
          align: Alignment(0.0, -0.5),
          size: 78,
          style: PropSmashStyle.shatter,
        ),
        RoomProp(
          id: 'lamp',
          label: 'Art lamp',
          icon: Icons.light,
          color: Color(0xFFFFE082),
          align: Alignment(0.6, -0.1),
          size: 52,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'vase',
          label: 'Crystal vase',
          icon: Icons.local_florist,
          color: Color(0xFFF8BBD0),
          align: Alignment(0.55, 0.35),
          size: 50,
          style: PropSmashStyle.shatter,
        ),
      ],
    ),
    RoomSetup(
      id: 'dorm',
      name: 'Dorm Room',
      subtitle: 'Roommate-safe rage',
      icon: Icons.bed,
      accent: Color(0xFF81D4FA),
      gradient: [Color(0xFF1565C0), Color(0xFF1A1A2E)],
      props: [
        RoomProp(
          id: 'laptop',
          label: 'Laptop',
          icon: Icons.laptop_mac,
          color: Color(0xFF90A4AE),
          align: Alignment(0.1, 0.05),
          size: 54,
          style: PropSmashStyle.crack,
        ),
        RoomProp(
          id: 'ramen',
          label: 'Ramen cup',
          icon: Icons.ramen_dining,
          color: Color(0xFFFFCC80),
          align: Alignment(-0.45, 0.15),
          size: 44,
          style: PropSmashStyle.spill,
          throwable: true,
        ),
        RoomProp(
          id: 'poster',
          label: 'Poster',
          icon: Icons.image,
          color: Color(0xFFEF9A9A),
          align: Alignment(0.5, -0.35),
          size: 58,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'chair',
          label: 'Desk chair',
          icon: Icons.event_seat,
          color: Color(0xFF78909C),
          align: Alignment(0.5, 0.45),
          size: 60,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'fridge',
          label: 'Mini fridge',
          icon: Icons.kitchen,
          color: Color(0xFF80CBC4),
          align: Alignment(-0.55, 0.4),
          size: 56,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'lamp',
          label: 'Desk lamp',
          icon: Icons.lightbulb,
          color: Color(0xFFFFF59D),
          align: Alignment(-0.2, -0.25),
          size: 46,
          style: PropSmashStyle.tipOver,
        ),
      ],
    ),
    RoomSetup(
      id: 'server',
      name: 'Server Room',
      subtitle: 'Blinkenlights beware',
      icon: Icons.dns,
      accent: Color(0xFF69F0AE),
      gradient: [Color(0xFF004D40), Color(0xFF0A0A12)],
      props: [
        RoomProp(
          id: 'rack',
          label: 'Server rack',
          icon: Icons.dns,
          color: Color(0xFF546E7A),
          align: Alignment(-0.4, -0.05),
          size: 72,
          style: PropSmashStyle.explode,
        ),
        RoomProp(
          id: 'monitor',
          label: 'Monitor',
          icon: Icons.monitor,
          color: Color(0xFF69F0AE),
          align: Alignment(0.4, -0.1),
          size: 58,
          style: PropSmashStyle.crack,
        ),
        RoomProp(
          id: 'keyboard',
          label: 'Keyboard',
          icon: Icons.keyboard,
          color: Color(0xFF78909C),
          align: Alignment(0.35, 0.3),
          size: 50,
          style: PropSmashStyle.smashFlat,
        ),
        RoomProp(
          id: 'cable',
          label: 'Cable bin',
          icon: Icons.cable,
          color: Color(0xFFFF8A65),
          align: Alignment(-0.5, 0.45),
          size: 50,
          style: PropSmashStyle.tipOver,
        ),
        RoomProp(
          id: 'coffee',
          label: 'Coffee',
          icon: Icons.coffee,
          color: Color(0xFFBCAAA4),
          align: Alignment(0.05, 0.15),
          size: 42,
          style: PropSmashStyle.spill,
          throwable: true,
        ),
        RoomProp(
          id: 'fan',
          label: 'Cooling fan',
          icon: Icons.air,
          color: Color(0xFF80CBC4),
          align: Alignment(0.55, 0.45),
          size: 52,
          style: PropSmashStyle.explode,
        ),
      ],
    ),
  ];
}
